### ISSUE TITLE
AsyncModbusSerialClient is not working with multiple slaves concurrently

### ISSUE THREAD

**Issue by KarolyPoka** [pymodbus-dev/pymodbus#1606]
### Versions

- Python: 3.9
- OS: Windows 10
- Pymodbus: 3.3.1
- Modbus Hardware: several RTU slave devices connected to a distribution box. The distribution box is connected to one USB serial serial port

### Pymodbus Specific
- Client: rtu- async

### Description

I am trying to read modbus registers from several slave devices concurrently, using asynchronous client. 

### Code and Logs
This version of the main() function is always executed with a timeout error
```python
import asyncio
import datetime
from pymodbus import pymodbus_apply_logging_config
from pymodbus.client import AsyncModbusSerialClient
from pymodbus.transaction import ModbusRtuFramer
from DeviceModbusRegisterMap import registers


async def run_async_client(port):
    """Run async client."""

    # activate debugging
    pymodbus_apply_logging_config("DEBUG")
    print("get client")

    client = AsyncModbusSerialClient(
        port,
        framer=ModbusRtuFramer,
        timeout=0.2,
        # retries=3,
        # retry_on_empty=False,
        # close_comm_on_error=False,
        # strict=True,
        baudrate=115200,
        # bytesize=8,
        # parity="N",
        stopbits=2,
        handle_local_echo=True,
    )

    print("connect to server")
    await client.connect()
    # test client is connected
    print("Client connected: ", client.connected)

    return client


async def run_calls(client, slave_address):
    debug_start = datetime.datetime.now()
    rr = await client.read_holding_registers(1288-1, 8, slave=slave_address)
    print(rr)
    debug_end = datetime.datetime.now()
    duration = debug_end - debug_start
    print("reading register time: ", duration.total_seconds())


async def run_trough(client, slave_address):
    debug_start = datetime.datetime.now()

    items = list(registers.items())
    slice = items[6:10]
    sliced_registers = dict(slice)

    for value in sliced_registers.values():
        rr = await client.read_holding_registers(value["adr"] - 1, value["len"], slave=slave_address)

    debug_end = datetime.datetime.now()
    duration = debug_end - debug_start
    print(slave_address, " reading register time: ", duration.total_seconds())


async def main():
    client = await run_async_client("COM10")

    task1 = asyncio.create_task(run_trough(client=client, slave_address=5))
    task2 = asyncio.create_task(run_trough(client=client, slave_address=6))
    await asyncio.gather(task1, task2)


if __name__ == "__main__":
    asyncio.run(main(), debug=True)
```
OUTPUT
```python
get client
connect to server
Client connected:  True
2023-06-15 13:45:39,141 DEBUG logging:102 Connecting to None.
2023-06-15 13:45:39,141 DEBUG logging:102 Connecting comm
2023-06-15 13:45:39,151 DEBUG logging:102 Connected to comm
2023-06-15 13:45:39,152 DEBUG logging:102 send: 0x5 0x3 0x9 0xa7 0x0 0x6 0x76 0x33
2023-06-15 13:45:39,153 DEBUG logging:102 Adding transaction 5
2023-06-15 13:45:39,153 DEBUG logging:102 send: 0x6 0x3 0x9 0xa7 0x0 0x6 0x76 0x0
2023-06-15 13:45:39,153 DEBUG logging:102 Adding transaction 6
2023-06-15 13:45:39,471 DEBUG logging:102 Connection lost comm due to None
2023-06-15 13:45:39,471 DEBUG logging:102 Getting transaction 5
2023-06-15 13:45:39,471 DEBUG logging:102 Getting transaction 6
Executing <Handle SerialTransport._call_connection_lost(None) created at D:\SVN\trunk\Scripts\Hamilton Device Manager 2\HDM2\venv\lib\site-packages\pymodbus\transport\serial_asyncio\__init__.py:415> took 0.125 seconds
Traceback (most recent call last):
  File "C:\Users\KPoka\AppData\Local\Programs\Python\Python39\lib\asyncio\tasks.py", line 490, in wait_for
    return fut.result()
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\SVN\trunk\Scripts\Hamilton Device Manager 2\HDM2\endless_pain.py", line 73, in <module>
    asyncio.run(main(), debug=True)
  File "C:\Users\KPoka\AppData\Local\Programs\Python\Python39\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\KPoka\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "D:\SVN\trunk\Scripts\Hamilton Device Manager 2\HDM2\endless_pain.py", line 68, in main
    await asyncio.gather(task1, task2)
  File "D:\SVN\trunk\Scripts\Hamilton Device Manager 2\HDM2\endless_pain.py", line 56, in run_trough
    rr = await client.read_holding_registers(value["adr"] - 1, value["len"], slave=slave_address)
  File "D:\SVN\trunk\Scripts\Hamilton Device Manager 2\HDM2\venv\lib\site-packages\pymodbus\client\base.py", line 198, in async_execute
    resp = await asyncio.wait_for(req, timeout=self.params.timeout)
  File "C:\Users\KPoka\AppData\Local\Programs\Python\Python39\lib\asyncio\tasks.py", line 492, in wait_for
    raise exceptions.TimeoutError() from exc
asyncio.exceptions.TimeoutError

Process finished with exit code 1

```
BUT if I add a sleep function between the 2 task creations in the main() function like this, it works:
```python
async def main():
    client = await run_async_client("COM10")

    task1 = asyncio.create_task(run_trough(client=client, slave_address=5))
    await asyncio.sleep(0.1)
    task2 = asyncio.create_task(run_trough(client=client, slave_address=6))
    await asyncio.gather(task1, task2)
```
OUTPUT
```python
get client
connect to server
2023-06-15 13:49:50,179 DEBUG logging:102 Connecting to None.
2023-06-15 13:49:50,179 DEBUG logging:102 Connecting comm
Client connected:  True
2023-06-15 13:49:50,194 DEBUG logging:102 Connected to comm
2023-06-15 13:49:50,195 DEBUG logging:102 send: 0x5 0x3 0x9 0xa7 0x0 0x6 0x76 0x33
2023-06-15 13:49:50,195 DEBUG logging:102 Adding transaction 5
2023-06-15 13:49:50,213 DEBUG logging:102 recv: 0x5 0x3 0xc 0x0 0x0 0x0 0x80 0x9 0x7c 0x43 0xa0 0x0 0x0 0x0 0x0 0x5 0xf2
2023-06-15 13:49:50,213 DEBUG logging:102 recv: 0x5 0x3 0xc 0x0 0x0 0x0 0x80 0x9 0x7c 0x43 0xa0 0x0 0x0 0x0 0x0 0x5 0xf2
2023-06-15 13:49:50,213 DEBUG logging:102 Getting Frame - 0x3 0xc 0x0 0x0 0x0 0x80 0x9 0x7c 0x43 0xa0 0x0 0x0 0x0 0x0
2023-06-15 13:49:50,213 DEBUG logging:102 Factory Response[ReadHoldingRegistersResponse': 3]
2023-06-15 13:49:50,213 DEBUG logging:102 Frame advanced, resetting header!!
2023-06-15 13:49:50,213 DEBUG logging:102 Getting transaction 5
2023-06-15 13:49:50,214 DEBUG logging:102 send: 0x5 0x3 0x9 0xc7 0x0 0x6 0x76 0x2d
2023-06-15 13:49:50,214 DEBUG logging:102 Adding transaction 5
2023-06-15 13:49:50,228 DEBUG logging:102 recv: 0x5 0x3 0xc 0x0 0x4 0x0 0x0 0x2e 0xff 0x41 0xf8 0x0 0x0 0x0 0x0 0xa0 0x1d
2023-06-15 13:49:50,228 DEBUG logging:102 recv: 0x5 0x3 0xc 0x0 0x4 0x0 0x0 0x2e 0xff 0x41 0xf8 0x0 0x0 0x0 0x0 0xa0 0x1d
2023-06-15 13:49:50,228 DEBUG logging:102 Getting Frame - 0x3 0xc 0x0 0x4 0x0 0x0 0x2e 0xff 0x41 0xf8 0x0 0x0 0x0 0x0
2023-06-15 13:49:50,228 DEBUG logging:102 Factory Response[ReadHoldingRegistersResponse': 3]
2023-06-15 13:49:50,228 DEBUG logging:102 Frame advanced, resetting header!!
2023-06-15 13:49:50,228 DEBUG logging:102 Getting transaction 5
2023-06-15 13:49:50,229 DEBUG logging:102 send: 0x5 0x3 0x9 0xe7 0x0 0x6 0x77 0xe7
2023-06-15 13:49:50,229 DEBUG logging:102 Adding transaction 5
2023-06-15 13:49:50,244 DEBUG logging:102 recv: 0x5 0x3 0xc 0x0 0x0 0x0 0x80 0x59 0x5b 0x43 0xa0 0x0 0x0 0x0 0x0 0x57 0xcc
2023-06-15 13:49:50,244 DEBUG logging:102 recv: 0x5 0x3 0xc 0x0 0x0 0x0 0x80 0x59 0x5b 0x43 0xa0 0x0 0x0 0x0 0x0 0x57 0xcc
2023-06-15 13:49:50,244 DEBUG logging:102 Getting Frame - 0x3 0xc 0x0 0x0 0x0 0x80 0x59 0x5b 0x43 0xa0 0x0 0x0 0x0 0x0
2023-06-15 13:49:50,244 DEBUG logging:102 Factory Response[ReadHoldingRegistersResponse': 3]
2023-06-15 13:49:50,244 DEBUG logging:102 Frame advanced, resetting header!!
2023-06-15 13:49:50,244 DEBUG logging:102 Getting transaction 5
2023-06-15 13:49:50,245 DEBUG logging:102 send: 0x5 0x3 0xa 0x7 0x0 0x6 0x76 0x55
2023-06-15 13:49:50,245 DEBUG logging:102 Adding transaction 5
2023-06-15 13:49:50,259 DEBUG logging:102 recv: 0x5 0x3 0xc 0x0 0x4 0x0 0x0 0x31 0x5f 0x41 0xf8 0x0 0x0 0x0 0x0 0x41 0x5b
2023-06-15 13:49:50,259 DEBUG logging:102 recv: 0x5 0x3 0xc 0x0 0x4 0x0 0x0 0x31 0x5f 0x41 0xf8 0x0 0x0 0x0 0x0 0x41 0x5b
2023-06-15 13:49:50,259 DEBUG logging:102 Getting Frame - 0x3 0xc 0x0 0x4 0x0 0x0 0x31 0x5f 0x41 0xf8 0x0 0x0 0x0 0x0
2023-06-15 13:49:50,259 DEBUG logging:102 Factory Response[ReadHoldingRegistersResponse': 3]
2023-06-15 13:49:50,259 DEBUG logging:102 Frame advanced, resetting header!!
2023-06-15 13:49:50,259 DEBUG logging:102 Getting transaction 5
5  reading register time:  0.065225
2023-06-15 13:49:50,291 DEBUG logging:102 send: 0x6 0x3 0x9 0xa7 0x0 0x6 0x76 0x0
2023-06-15 13:49:50,291 DEBUG logging:102 Adding transaction 6
2023-06-15 13:49:50,305 DEBUG logging:102 recv: 0x6 0x3 0xc 0x0 0x0 0x0 0x80 0x22 0xfc 0x43 0x55 0x0 0x0 0x0 0x0 0x8 0x85
2023-06-15 13:49:50,305 DEBUG logging:102 recv: 0x6 0x3 0xc 0x0 0x0 0x0 0x80 0x22 0xfc 0x43 0x55 0x0 0x0 0x0 0x0 0x8 0x85
2023-06-15 13:49:50,305 DEBUG logging:102 Getting Frame - 0x3 0xc 0x0 0x0 0x0 0x80 0x22 0xfc 0x43 0x55 0x0 0x0 0x0 0x0
2023-06-15 13:49:50,305 DEBUG logging:102 Factory Response[ReadHoldingRegistersResponse': 3]
2023-06-15 13:49:50,305 DEBUG logging:102 Frame advanced, resetting header!!
2023-06-15 13:49:50,305 DEBUG logging:102 Getting transaction 6
2023-06-15 13:49:50,306 DEBUG logging:102 send: 0x6 0x3 0x9 0xc7 0x0 0x6 0x76 0x1e
2023-06-15 13:49:50,306 DEBUG logging:102 Adding transaction 6
2023-06-15 13:49:50,321 DEBUG logging:102 recv: 0x6 0x3 0xc 0x0 0x2 0x0 0x0 0xc6 0x2a 0x43 0x96 0x0 0x0 0x0 0x0 0x9e 0x9c
2023-06-15 13:49:50,321 DEBUG logging:102 recv: 0x6 0x3 0xc 0x0 0x2 0x0 0x0 0xc6 0x2a 0x43 0x96 0x0 0x0 0x0 0x0 0x9e 0x9c
2023-06-15 13:49:50,321 DEBUG logging:102 Getting Frame - 0x3 0xc 0x0 0x2 0x0 0x0 0xc6 0x2a 0x43 0x96 0x0 0x0 0x0 0x0
2023-06-15 13:49:50,321 DEBUG logging:102 Factory Response[ReadHoldingRegistersResponse': 3]
2023-06-15 13:49:50,321 DEBUG logging:102 Frame advanced, resetting header!!
2023-06-15 13:49:50,321 DEBUG logging:102 Getting transaction 6
2023-06-15 13:49:50,322 DEBUG logging:102 send: 0x6 0x3 0x9 0xe7 0x0 0x6 0x77 0xd4
2023-06-15 13:49:50,323 DEBUG logging:102 Adding transaction 6
2023-06-15 13:49:50,336 DEBUG logging:102 recv: 0x6 0x3 0xc 0x0 0x0 0x0 0x80 0x66 0x11 0x43 0x55 0x0 0x0 0x0 0x0 0x30 0x48
2023-06-15 13:49:50,336 DEBUG logging:102 recv: 0x6 0x3 0xc 0x0 0x0 0x0 0x80 0x66 0x11 0x43 0x55 0x0 0x0 0x0 0x0 0x30 0x48
2023-06-15 13:49:50,336 DEBUG logging:102 Getting Frame - 0x3 0xc 0x0 0x0 0x0 0x80 0x66 0x11 0x43 0x55 0x0 0x0 0x0 0x0
2023-06-15 13:49:50,336 DEBUG logging:102 Factory Response[ReadHoldingRegistersResponse': 3]
2023-06-15 13:49:50,336 DEBUG logging:102 Frame advanced, resetting header!!
2023-06-15 13:49:50,336 DEBUG logging:102 Getting transaction 6
2023-06-15 13:49:50,336 DEBUG logging:102 send: 0x6 0x3 0xa 0x7 0x0 0x6 0x76 0x66
2023-06-15 13:49:50,337 DEBUG logging:102 Adding transaction 6
2023-06-15 13:49:50,351 DEBUG logging:102 recv: 0x6 0x3 0xc 0x0 0x2 0x0 0x0 0xc6 0xf 0x43 0x96 0x0 0x0 0x0 0x0 0xea 0x5e
2023-06-15 13:49:50,351 DEBUG logging:102 recv: 0x6 0x3 0xc 0x0 0x2 0x0 0x0 0xc6 0xf 0x43 0x96 0x0 0x0 0x0 0x0 0xea 0x5e
2023-06-15 13:49:50,351 DEBUG logging:102 Getting Frame - 0x3 0xc 0x0 0x2 0x0 0x0 0xc6 0xf 0x43 0x96 0x0 0x0 0x0 0x0
2023-06-15 13:49:50,351 DEBUG logging:102 Factory Response[ReadHoldingRegistersResponse': 3]
2023-06-15 13:49:50,351 DEBUG logging:102 Frame advanced, resetting header!!
2023-06-15 13:49:50,351 DEBUG logging:102 Getting transaction 6
6  reading register time:  0.061069

Process finished with exit code 0
```
I assume something goes wrong with the COM port handling when the second task starts, but I cant wrap my head around why the sleep solves this between the task creations??? How is it possible to read from several slaves asynchronously, connected to the same serial port? Thanks a lot in advance for your help!

**Comment by janiversen** [comment]
You cannot run calls on one connection from 2 tasks, at least not unless you add some locking.

**Comment by janiversen** [comment]
simply run the calls serialized, you only have one comm line so parallel will cause problem.

e.g. use one task, and have the 2 calls in there.

**Comment by janiversen** [comment]
Close,  because it not a pymodbus issue but a wrong usage.

**Comment by KarolyPoka** [comment]
Thanks a lot!
