### ISSUE TITLE
UNKNOWN EXCEPTION name 'serial' is not defined

### ISSUE THREAD

**Issue by brkbrc** [pymodbus-dev/pymodbus#1742]
### Versions

- Python: 3.9
- OS: raspberryPi OS
- Pymodbus: Dev Branch (tried also main branch)
- Modbus Hardware (if used): FTDI USB 485 converter 

### Pymodbus Specific

- Client: rtu - async

### Description

I am trying to execute the example from the documentation for async client communication, ./client_async.py
I want to use the USB FTDI Serial RS485 device to connect to a inverter via Modbus

### Code and Logs

I execute following:
(NewEnv) root@raspberrypi:/home/cmd/NewEnv/pymodbus# ./client_async.py -c serial -f rtu --baudrate 9600

I get following error:

(NewEnv) root@raspberrypi:/home/cmd/NewEnv/pymodbus# ./client_async.py -c serial -f rtu --baudrate 9600
INFO:/home/cmd/NewEnv/pymodbus/./client_async.py:### Create client object
INFO:/home/cmd/NewEnv/pymodbus/./client_async.py:### Client starting
2023-08-21 21:19:08,546 WARNING logging:108 Failed to connect UNKNOWN EXCEPTION name 'serial' is not defined
WARNING:pymodbus.logging:Failed to connect UNKNOWN EXCEPTION name 'serial' is not defined
Traceback (most recent call last):
  File "/home/cmd/NewEnv/pymodbus/./client_async.py", line 153, in <module>
    asyncio.run(main(), debug=True)  # pragma: no cover
  File "/usr/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/home/cmd/NewEnv/pymodbus/./client_async.py", line 149, in main
    await run_async_client(testclient, modbus_calls=run_a_few_calls)
  File "/home/cmd/NewEnv/pymodbus/./client_async.py", line 126, in run_async_client
    await client.connect()
  File "/home/cmd/NewEnv/pymodbus/pymodbus/client/serial.py", line 84, in connect
    return await self.transport_connect()
  File "/home/cmd/NewEnv/pymodbus/pymodbus/transport/transport.py", line 250, in transport_connect
    self.transport, _protocol = await asyncio.wait_for(
  File "/usr/lib/python3.9/asyncio/tasks.py", line 481, in wait_for
    return fut.result()
  File "/home/cmd/NewEnv/pymodbus/pymodbus/transport/transport_serial.py", line 233, in create_serial_connection
    transport = SerialTransport(loop, protocol, *args, **kwargs)
  File "/home/cmd/NewEnv/pymodbus/pymodbus/transport/transport_serial.py", line 20, in __init__
    self.sync_serial = serial.serial_for_url(*args, **kwargs)
NameError: name 'serial' is not defined
(NewEnv) root@raspberrypi:/home/cmd/NewEnv/pymodbus#

**Comment by janiversen** [comment]
please install pyserial as described in the documentation.

**Comment by brkbrc** [comment]
@janiversen I have pyserial installed


` pip install pyserial
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Requirement already satisfied: pyserial in /usr/local/lib/python3.9/dist-package         s (3.5)
`

In the documentation of pymodbus I do not find anything specific for pyserial
